name: CI

on:
  push:
    paths:
      - clippy.toml
      - rust-toolchain.toml
      - src/**
      - Dioxus.toml
      - rustfmt.toml
      - taplo.toml
      - Cargo.toml

env:
  RUST_BACKTRACE: 1

jobs:
  fmt:
    name: Format (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt --all --verbose -- --check

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - run: cargo check --all-targets --all-features

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo doc --no-deps --all-features --document-private-items
        env:
          RUSTDOCFLAGS: -Dwarnings

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - with:
          toolchain: nightly
          components: clippy
        run: cargo clippy --all-targets --all-features --future-incompat-report

  doctests:
    name: Documentation tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - run: cargo test --doc --all-features --verbose

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      # WARN: Could miss cases where code stops working with a feature enabled, but works without it.
      - run: cargo test --all-targets  dioxus:

  dioxus:
    name: Dioxus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - run: cargo install dioxus-cli --version 0.7.1
      - run: dx fmt --check
      - run: dx check --verbose
