name: CI

on:
  push:
    paths:
      - .github/workflows/**
      - clippy.toml
      - rust-toolchain.toml
      - src/**
      - Dioxus.toml
      - rustfmt.toml
      - taplo.toml
      - Cargo.toml

env:
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: -Dwarnings
  SQLX_OFFLINE: true

jobs:
  fmt:
    name: Format (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt --all --verbose -- --check

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - run: cargo check --all-targets
      - run: cargo check --all-targets -F server

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo doc --no-deps --document-private-items
      - run: cargo doc --no-deps --document-private-items -F server 

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - run: cargo clippy --all-targets --future-incompat-report
      - run: cargo clippy --all-targets --future-incompat-report -F server

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - run: cargo test --all-targets

  dioxus:
    name: Dioxus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall dioxus-cli@0.7.1 --force --no-confirm
      - run: dx fmt --check
      - run: dx check --verbose
