name: CI

on:
  push:

env:
  RUSTDOCFLAGS: "-Dwarnings"

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: |
            rustfmt
            clippy
          target: wasm32-unknown-unknown

      - name: Install Dioxus CLI
        run: curl -sSL https://dioxus.dev/install.sh | bash

      - name: Format (Rust)
        run: cargo fmt -- --check

      - name: Format (RSX)
        run: dx fmt --check

      - name: Compile
        run: dx check

      - name: Lint
        run: cargo clippy --workspace --all-targets

      - name: Build documentation
        run: cargo rustdoc -- --document-private-items -Z unstable-options --check

      - name: Tests
        run: cargo test --verbose
